stages:
  default-train:
    cmd: python -m src.model.train default
    deps:
    - data/oxford-iiit-pet
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/default.pt
  contrastive-train:
    cmd: python -m src.model.train contrastive
    deps:
    - data/oxford-iiit-pet
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/contrastive.pt
  default-evaluate:
    cmd: python -m src.model.evaluate default
    deps:
    - data/oxford-iiit-pet
    - models/default.pt
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/evaluate.py
    - src/model/train.py
    outs:
    - data/evals/default_cam.png
  contrastive-evaluate:
    cmd: python -m src.model.evaluate contrastive
    deps:
    - data/oxford-iiit-pet
    - models/contrastive.pt
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/evaluate.py
    - src/model/train.py
    outs:
    - data/evals/contrastive_cam.png
