stages:
  default-train:
    cmd: python -m src.model.train default no-checkpoint
    deps:
    - data/oxford-iiit-pet
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/default_last.pt
    - models/default_best.pt
  contrastive-train:
    cmd: python -m src.model.train contrastive no-checkpoint
    deps:
    - data/oxford-iiit-pet
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/loss.py
    - src/model/train.py
    outs:
    - models/contrastive_last.pt
    - models/contrastive_best.pt
  default-evaluate:
    cmd: python -m src.model.evaluate default_best visualize
    deps:
    - data/oxford-iiit-pet
    - models/default_best.pt
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/evaluate.py
    - src/model/train.py
    outs:
    - data/evals/default_cam.png
  contrastive-evaluate:
    cmd: python -m src.model.evaluate contrastive_best visualize
    deps:
    - data/oxford-iiit-pet
    - models/contrastive_best.pt
    - src/const.py
    - src/data/oxford_iiit_pet.py
    - src/model/arch.py
    - src/model/evaluate.py
    - src/model/train.py
    outs:
    - data/evals/contrastive_cam.png
